# Generated by Django 5.0.4 on 2024-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetails",
            name="stripe_payment_intent",
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="payment_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
