# Generated by Django 5.0.4 on 2024-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_orderdetails_stripe_payment_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_sales",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_sales_amount",
            field=models.IntegerField(default=0),
        ),
    ]
