# Generated by Django 5.0.4 on 2024-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_product_total_sales_product_total_sales_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Goods", "Goods"), ("Services", "Services")],
                default="Goods",
                max_length=20,
            ),
        ),
    ]
