# Generated by Django 5.0.4 on 2024-05-04 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
